</div>
	<div class="logo logo1">
		<a href="index.php">D'ORIGEN</a>
	</div>
</div>

		<div class="content">
		 	<div class="services-section">
		 		<div class="container">
						<h3>NUESTROS PRODUCTOS</h3>
						<div class="services-grids">
						<div class="service1">
						<div class="col-md-4 services-grid wow bounceInLeft animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">

						<div id="contenedor">
						  <section>
							  <div id="contienecarrito">
							    <div id="carrito" style="background:rgb(200,200,200); color:black;">Carrito
							    </div>
							  <a href='php/destruir.php'><button>Vaciar carrito</button></a>
							  <a href='confirmar.php'><button>Confirmar compra</button></a>
							  </div>
							</section>
						</div>

						</div>
						</div>
						<div class="clearfix"></div>
						</div>
