</div>
	<div class="logo logo1">
		<a href="index.php">D'ORIGEN</a>
		</div>
		</div>
</div>
		<div class="maine">
		<div class="container">
			<div class="contact">
					<div class="contact-head text-center">
						<h3>COMUNICATE CON NOSOTROS</h3>
					</div>

							<form>
								<div class="contact-form-row">
									<div>
										<span>NOMBRE :</span>
										<input type="text" class="text" value="" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '';}">
									</div>
									<div>
										<span>CORREO :</span>
										<input type="text" class="text" value="" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '';}">
									</div>
									<div>
										<span>TEMA:</span>
										<input type="text" class="text" value="" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '';}">
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="clearfix"> </div>
								<div class="contact-form-row2 wow bounceInLeft animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
									<span>MENSAJE :</span>
									<textarea> </textarea>
								</div>
								<input type="submit" value="ENVIAR">
							</form>
						</div>
						<!----- contact-form ------>
					</div>

			</div>
		</div>
	</div>


		<div class="maine">
		<div class="container">
			<div class="contact">
					<div class="contact-head text-center">
						<h3>NUESTROS DATOS</h3>
					</div>
					</div>

<div class="col-md-3 header-grid">
<div class="header-img2 wow fadeInDownBig animated animated" data-wow-delay="0.4s">
	<img src="img/11111.png"" class="img-responsive" alt="/">

					<h4>TELEFONOS</h4>
					<li>052405060</li>
					<li>998868861</li>
					</div>
					</div>
	<div class="col-md-3 header-grid">
		<div class="header-img2 wow fadeInDownBig animated animated" data-wow-delay="0.4s">
	<img src="img/22222.png"" class="img-responsive" alt="/">
					<h4>CORREO</h4>
					<li>sandratbn54@gmail.com</li>
					<li>grupobrisar@gmail.com</li>
					</div>
					</div>

	<div class="col-md-3 header-grid">
		<div class="header-img3 wow fadeInUpBig animated animated" data-wow-delay="0.4s">
	<img src="img/33333.png"" class="img-responsive" alt="/">
					<h4>DIRECCIÓN</h4>
					<li>Yarada Los Palos</li>
					<li>Tacna Centro puesto 4B</li>
					</div>
					</div>
					<div class="col-md-3 header-grid">
						<div class="header-img4 wow bounceInRight animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
	<img src="img/44444.pNg"" class="img-responsive" alt="/">
					<h4>FACEBOOK</h4>
					<li>@alimentosdeorigen/</li>
					<li>@sandra.bricenonavarro/</li>
					</div>
</div>
</div>

		</ul>
		</div>
