
	</div>
	<div class="logo logo1">
		<a href="index.php">D'ORIGEN</a>
		</div>

</div>
</div>
		 <div class="content">
		 <div class="aboutus-section">
		 <div class="container">
		 <h3>N O S O T R O S</h3>
		 <div class="aboutus-grids">
		 <div class="col-md-5 left-grid wow bounceInLeft animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
		 <div class="aboutus1">
	</ul>
		 </div>
		 <div class="aboutus2">
		 <h4>OBJETIVOS</h4>
		 <div class="ab1">
			<li>Cumplir puntualmente con los tiempos de entrega establecidos en las órdenes de compra o servicio.</li>
	     <li>Medir el cumplimiento del Sistema de Gestión de la Calidad que desarrollamos de acuerdo a la norma BPMG, tomada como referencia.</li>
	     <li>Seleccionar proveedores que cumplan los estándares de Calidad en la comercialización de sus materias primas para la elaboración de nuestro producto terminado.</li>
	     <li>Medir la satisfacción de nuestros clientes de acuerdo a los productos y servicios brindados.</li>
	     <li>Capacitar, entrenar y evaluar frecuentemente al personal involucrado en el desarrollo de nuestros procesos.</li>

		 <a href="#">GRUPO BRISAR</a>
		</div>
		</div>
		 <div class="clearfix"></div>
		 </div>
 <div class="col-md-7 right-grid wow bounceInRight animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
      <div class="aboutus3">
       <h5></h5>
       <h5>Misión:</h5>
        <h5>“Somos una empresa que procesa aceitunas de mesa de optima calidad, comprometida con la satisfacción de nuestros consumidores, asegurando la fidelidad de nuestros clientes y promoviendo el crecimiento personal de nuestros colaboradores”.</h5>
        <h5>Visión:</h5>
        <h5>“Ser líder como empresa exportadora de aceitunas de mesa y sus derivados en el sur del Perú, con posicionamiento nacional e internacional”.</h5>
      </div>
</div>

 <div class="content">
		 		 <div class="services-section">
		 	<div class="container">


	`					</div>
					<div class="clearfix"></div>
					</div>

	  <div class="aboutus4">
       <h4>C E R T I F I C A D O S</h4>
      <div class="col-md-4 team-grid">
	<img src="img/p19.jpeg" class="img-responsive" alt="" />
	  <h5>CURSO-TALLER</h5>
	  <p>Buenas prácticas de manufactura y plan de higiene y saneamiento para MYPES del sector alimentos y agroindustria</p>
      </div>

	   <div class="col-md-4 team-grid">
	   <img src="img/p20.jpg" class="img-responsive" alt="" />
	  <h5>DIGEMID</h5>
	  <p>Buenas prácticas en el almacenaje</p>
      </div>
	   <div class="col-md-4 team-grid">
	  <img src="img/p21.jpeg" class="img-responsive" alt="" />
	  <h5>CURSO-TALLER</h5>
	  <p>Análisis físico sensorial en el control de calidad de aceitunas de mesa</p>
      </div>
      </div>
		 <div class="clearfix"></div>
		 </div>
			</div>
			</div>
			</div>
		  <div class="categories-section">
		   <div class="container">
		   <div class="footer-grids">
			<div class="col-md-4 up wow bounceInLeft animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
		</div>
		
		<div class="clearfix"></div>
		</div>
		</div>
		</div>
		</div>
		<div class="categories-section">
		<div class="container">
		<div class="footer-grids">
		<div class="col-md-4 up wow bounceInLeft animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
