</div>
<div class="logo logo1">
  <a href="index.html">D'ORIGEN</a>
  </div>

</div>
</div>
  <div class="content">
  <!-- 404
<div class="main wow bounceIn animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
  <div class="error-404 text-center">
      <h1>404</h1>
      <p>this link dead link</p>
      <a class="b-home" href="index.html">Back to Home</a>
      -->
    </div>
</div>
<!-- 404
-->
</div>
     <div class="categories-section">
     <div class="container">
     <div class="footer-grids">
    <div class="col-md-4 up wow bounceInLeft animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">



  <div class="clearfix"></div>
        </div>
     </div>
     </div>
     <div class="work-section wow bounceIn animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
     <div class="container">
     <h3>NUESTRAS ULTIMAS NOTICIAS</h3>
     <div class="latest-grids">
     <div class="latest-grid1">
      <div class="col-md-3 latest-grid work">
        <a href="img/img2.jpg" class="swipebox"><img src="img/img2.jpg" class="img-responsive" alt="/">

          </div></a>
        <div class="col-md-3 latest-grid work">
        <a href="img/img3.jpeg" class="swipebox"><img src="img/img3.jpeg" class="img-responsive" alt="/">

          </div></a>
     <div class="clearfix"></div>
     </div>
     <div class="clearfix"></div>
     </div>
     </div>
     </div>
     <div class="news-section">
     <div class="container">

  </ul>
  </div>
