
<div class="clearfix"></div>
</div>
</div>
</div>
<!-- 3 div cierran -->
<div class="footer-section">
<div class="container">
<div class="footer-top">
<div class="social-icons wow bounceInLeft animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
<a href="#"><i class="icon1"></i></a>
<a href="#"><i class="icon2"></i></a>
<a href="#"><i class="icon3"></i></a>
<a href="#"><i class="icon4"></i></a>
</div>
</div>
<div class="footer-middle wow fadeInDown Big animated animated" data-wow-delay="0.4s">
<div class="bottom-menu">
<ul>

<li><a href="index.php" class="active">INICIO</a></li><label>/</label>
<li><a href="nosotros.php">NOSOTROS</a></li><label>/</label>
<li><a href="promociones.php">PROMOCIONES</a></lPROMOCIONESi><label>/</label>
<li><a href="productos.php">PRODUCTOS</a></li><label>/</label>
<li><a href="noticias.php">NOTICIAS</a></li><label>/</label>
<li><a href="contacto.php">CONTACTO</a></li>

</ul>
</div>
</div>
<div class="footer-bottom wow bounceInRight animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
        <p> Copyright &copy;2017 <a href="http://w3layouts.com" target="target_blank"/a></p>
        </div>
<script type="text/javascript">
  $(document).on(function() {
    /*
    var defaults = {
        containerID: 'toTop', // fading element id
      containerHoverID: 'toTopHover', // fading element hover id
      scrollSpeed: 1200,
      easingType: 'linear'
    };
    */

    $().UItoTop({ easingType: 'easeOutQuart' });

  });
</script>
<a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
</div>
</div>
  </body>
</html>
<!--"  include "php/log.php"  "-->
