
	</div>
	<div class="logo logo1">
		<a href="index.php">D'ORIGEN</a>
		</div>

</div>
</div>
		 <div class="content">
		 		 <div class="services-section">
		 	<div class="container">
						<h3>PROMOCIONES</h3>
						<div class="services-grids">
						<div class="service1">
						<div class="col-md-4 services-grid wow bounceInLeft animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
						 <a href="img/p7.jpg" class="swipebox"><img src="img/p7.jpg" class="img-responsive" alt="" /></a>
						 <h5>ACEITUNA NEGRA EN FRASCO</h5>
					<p>Por la compra de 3 frascos de vidrio de aceituna negra,obten un descuento del 25% .</p>
						<a href="#" class="button1 hvr-shutter-in-vertical">Valido hasta julio 2017</a>
						</div>
						<div class="col-md-4 services-grid">
						<a href="img/p8.jpeg" class="swipebox"><img src="img/p8.jpeg" class="img-responsive" alt="" /></a>
						<h5>ACEITUNA NEGRA STAND UP</h5>
					<p>Lleva tu paquete de aceitunas negras en stand up en todas sus presentaciones a un modico precio .</p>
						<a href="#" class="button1 hvr-shutter-in-vertical">Valido hasta marzo 2018</a>
						</div>
						<div class="col-md-4 services-grid wow bounceInRight animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
						<a href="img/p9.jpg" class="swipebox"><img src="img/p9.jpg" class="img-responsive" alt="" /></a>
						<h5>MERMELADA DE HIGO EN FRASCO</h5>
					<p>Por la compra de 3 frascos de mermelada de higo llevate una bolsa de 250g.</p>
						<a href="#" class="button1 hvr-shutter-in-vertical">Valido hasta mayo 2018</a>
						</div>
						</div>
			<div class="clearfix"></div>
						</div>
						</div>
						</div>
					  </div>


</div>
</div>
		 <div class="content">
		 		 <div class="services-section">
		 	<div class="container">
						<h3>NUESTROS CLIENTES SATISFECHOS</h3>


		   <div class="service-section1">
				<div class="container">
					<div class="service-grids">
					<div class="col-md-4 service-grid wow bounceInLeft animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
					<img src="img/icon1.jpg" class="img-responsive" alt="/">
					<h4>FESTIVAL AGROINDUSTRIAL</h4>
					<p>Tacna - Perú</p>
					</div>
					<div class="col-md-4 service-grid wow fadeInDown Big animated animated" data-wow-delay="0.4s">
					<img src="img/icon2.jpg" class="img-responsive" alt="/">
						<h4>FERIA GASTRONOMICA</h4>
						<p>Cusco - Perú</p>
						</div>
					<div class="col-md-4 service-grid wow bounceInRight animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
					<img src="img/icon3.jpg" class="img-responsive" alt="/">
						<h4>FESTIVAL VEGANO</h4>
						<p>Arequipa - Perú</p>
						</div>
					<div class="clearfix"></div>
					</div>

					<div class="service-grids">
					<div class="col-md-4 service-grid wow bounceInLeft animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
					<img src="img/icon111.jpg" class="img-responsive" alt="/">
					<h4>FESTIVAL AGROINDUSTRIAL</h4>
					<p>Tacna - Perú</p>
					</div>
					<div class="col-md-4 service-grid wow fadeInDown Big animated animated" data-wow-delay="0.4s">
					<img src="img/icon222.jpg" class="img-responsive" alt="/">
						<h4>FERIA GASTRONOMICA</h4>
						<p>Cusco - Perú</p>
						</div>
					<div class="col-md-4 service-grid wow bounceInRight animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
					<img src="img/icon333.jpg" class="img-responsive" alt="/">
						<h4>FESTIVAL VEGANO</h4>
						<p>Arequipa - Perú</p>
	`					</div>
					<div class="clearfix"></div>
					</div>
		</ul>
		</div>
