</div>
	<div class="logo wow bounceIn animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
		<a href="index.php">D'ORIGEN</a>
		</div>
		<div class="header-bottom">
	<div class="header-grids">
	<div class="col-md-3 header-grid">
	<div class="header-img1 wow bounceInLeft animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
	<img src="img/icon4.jpg"" class="img-responsive" alt="/">
					<h4>UBICACION ESTRATEGICA</h4>
					<p>Nos encontramos fuera de Tacna,pero contamos con tiendas en el centro de la ciudad.</p>
					</div>
					</div>
	<div class="col-md-3 header-grid">
		<div class="header-img2 wow fadeInDownBig animated animated" data-wow-delay="0.4s">
	<img src="img/icon5.jpg"" class="img-responsive" alt="/">
					<h4>CALIDAD CERTIFICADA</h4>
					<p>Contamos con todos los registros sanitarios y con una capacitacion constante todo el tiempo.</p>
					</div>
					</div>

	<div class="col-md-3 header-grid">
		<div class="header-img3 wow fadeInUpBig animated animated" data-wow-delay="0.4s">
	<img src="img/icon6.jpg"" class="img-responsive" alt="/">
					<h4>INSTALACIONES ADECUADA</h4>
					<p>Nos preocupamos por contar con un espacio adecuado para la elaboracion de nuestros productos.</p>
					</div>
					</div>
					<div class="col-md-3 header-grid">
						<div class="header-img4 wow bounceInRight animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
	<img src="img/icon7.jpg"" class="img-responsive" alt="/">
					<h4>COSECHA DE CALIDAD</h4>
					<p>Invertimos tiempo para formar parte de la cosecha y asi garantizar la calidad de materia prima.</p>
					</div>
					</div>
	<div class="clearfix"></div>
	</div>
</div>
</div>
</div>
		 <div class="content">
			<div class="about-section">
				<div class="container">
					<h3>SOBRE NOSOTROS</h3>
				<div class="about-grids">
				<div class="col-md-5 about-img wow bounceInRight animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
			<img src="img/img1.jpg" class="img-responsive" alt="/">
				</div>
					<div class="col-md-7 about-grid wow bounceInLeft animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
						<h4>D' ORIGEN <br>
							<p>
							Somos una empresa  familiar que nace con el objetivo de procesar de manera artesanal los frutos de nuestras chacras y hacerlos llegar a mas hogares a precios justos.
						</p>
						<p>
							Llegamos al mercado a través de nuestra marca D´Origen, productos 100% naturales sin químicos ni persevantes, con un alto valor nutricional y un saber único.
						</p>
						<p>
							Participamos en el cultivo, cosecha, elaboración, envasado y comercialización; asegurando así la calidad de todos nuestros productos.
						</p>
						</h4>
				</div>
				<div class="clearfix"></div>
				</div>
				</div>
		   </div>
					<div class="clearfix"></div>
					</div>
		   </div>
		   </div>
		   <div class="work-section wow bounceIn animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">

		   <div class="container">
		   <h3>NUEVOS PRODUCTOS</h3>
		   <div class="news-grids">

	  </div>

					<div class="col-md-4 news-grid wow bounceInLeft animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
					<img src="img/img10.jpg" class="img-responsive" alt="/">
						<h4><a href="#">ALGARROBINA</a></h4>
					<p class="date">20 DE MARZO DEL 2017<a href="#"/a></p>
							<p></p>

						  </div>
					<div class="col-md-4 news-grid wow bounceInLeft animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
					<img src="img/img11.jpg" class="img-responsive" alt="/">
						<h4><a href="#">ACEITUNA VERDE</a></h4>
					<p class="date">05 DE ABRIL DEL 2017<a href="#"/a></p>
							<p></p>

						</div>
					<div class="col-md-4 news-grid wow bounceInRight animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
					<img src="img/img12.jpg" class="img-responsive" alt="/">
	        		<h4><a href="#">HIGO SECO</a></h4>
				<p class="date">16 DE JUNIO DEL 2017 <a href="#"/a></p>
							<p></p>

							</div>
